import Link from "next/link";
import { Award, FileCheck2, Printer, TrendingDown } from "lucide-react";
import { db } from "@/lib/db";
import { requireRole, hasRole, OFFICE, TEACHING } from "@/lib/session";
import { getResultAnalysis } from "@/lib/queries/exams";
import { formatPercent } from "@/lib/core/grading-core";
import { Badge, Card, CardHead, Empty, Meter, PageHead, Stat } from "@/components/ui/primitives";
import { GenerateButtons } from "./generate-button";

export const metadata = { title: "Report cards — Flanca" };

export default async function ReportCardsPage({
  searchParams,
}: {
  searchParams: Promise<{ term?: string }>;
}) {
  const actor = await requireRole(...TEACHING);
  const sp = await searchParams;
  const isOffice = hasRole(actor, ...OFFICE);

  // A subject-only teacher gets no school-wide view of every class's results —
  // same ownership rule as attendance: only the classes they are class teacher
  // of. Office keeps seeing everything.
  const onlyClassIds = isOffice
    ? undefined
    : Array.from(
        new Set(
          (
            await db.section.findMany({
              where: { schoolId: actor.schoolId, classTeacherId: actor.id },
              select: { classId: true },
            })
          ).map((s) => s.classId),
        ),
      );

  const terms = await db.examTerm.findMany({
    where: { schoolId: actor.schoolId, ...(onlyClassIds ? { classId: { in: onlyClassIds } } : {}) },
    orderBy: [{ sequenceOrder: "asc" }, { class: { sequenceOrder: "asc" } }],
    include: {
      class: { select: { name: true, sequenceOrder: true } },
      _count: { select: { reportCards: true } },
    },
  });

  // sp.term is user-supplied — only honour it if it names a term this actor is
  // actually allowed to see, or a teacher could read another class's results by
  // editing the URL.
  const selectedId =
    sp.term && terms.some((t) => t.id === sp.term)
      ? sp.term
      : (terms.find((t) => t._count.reportCards > 0)?.id ?? terms[0]?.id);
  const analysis = selectedId ? await getResultAnalysis(actor.schoolId, selectedId) : null;
  const selected = terms.find((t) => t.id === selectedId);

  return (
    <>
      <PageHead
        eyebrow="Academics"
        title="Report cards"
        sub="Generate a whole class in one action. Ranks handle ties correctly, and a card is a frozen snapshot — a reprint next year is identical to the one the parent holds."
      />

      <div className="grid items-start gap-5 lg:grid-cols-[300px_1fr]">
        {/* ── pick a class-term ── */}
        <Card className="overflow-hidden">
          <CardHead title="Class & term" hint="Pick which cards to work on" />
          {terms.length === 0 ? (
            <Empty
              title={
                !isOffice && onlyClassIds?.length === 0
                  ? "You are not a class teacher yet"
                  : "No exam terms yet"
              }
              hint={
                !isOffice && onlyClassIds?.length === 0
                  ? "Report cards are generated by each class's own class teacher. Ask the office if this looks wrong."
                  : !isOffice
                    ? "Your class has no exam terms — pre-primary classes (Nursery, LKG, UKG) are graded holistically rather than examined, so there is nothing to publish here."
                    : undefined
              }
            />
          ) : (
            <ul className="max-h-[560px] divide-y divide-line overflow-y-auto">
              {terms.map((t) => (
                <li key={t.id}>
                  <Link
                    href={`/app/report-cards?term=${t.id}`}
                    className={`flex items-center justify-between gap-2 px-4 py-2.5 transition-colors ${
                      t.id === selectedId ? "bg-brand-light" : "hover:bg-paper-2"
                    }`}
                  >
                    <div className="min-w-0">
                      <p className="truncate text-[13.5px] font-medium">
                        {t.class?.name ?? "—"} · {t.name}
                      </p>
                      <p className="text-[11.5px] text-ink-3">
                        {t._count.reportCards > 0
                          ? `${t._count.reportCards} cards`
                          : "not generated"}
                      </p>
                    </div>
                    {t.isPublished ? <Badge tone="good">Live</Badge> : null}
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </Card>

        <div className="space-y-5">
          {!analysis ? (
            <Card>
              <Empty title="Nothing selected" hint="Choose a class and term on the left." />
            </Card>
          ) : (
            <>
              <Card>
                <CardHead
                  title={`${analysis.term.className} — ${analysis.term.name}`}
                  hint={
                    analysis.term.isPublished
                      ? `Published${analysis.term.resultDate ? ` on ${analysis.term.resultDate.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}` : ""}`
                      : "Not published — parents cannot see these yet"
                  }
                  action={
                    <Link
                      href={`/app/report-cards/print?term=${analysis.term.id}`}
                      className="inline-flex items-center gap-1.5 text-[13px] font-semibold text-brand hover:underline"
                    >
                      <Printer className="size-3.5" /> Print all
                    </Link>
                  }
                />
                <div className="grid gap-3 px-5 py-4 sm:grid-cols-4">
                  <Stat label="Students" value={analysis.strength} sub={`${analysis.entered} with complete marks`} />
                  <Stat
                    label="Passed"
                    value={analysis.passed}
                    tone="good"
                    sub={analysis.entered > 0 ? formatPercent(Math.round((analysis.passed / analysis.entered) * 10000), 0) : "—"}
                  />
                  <Stat
                    label="Below pass"
                    value={analysis.failed}
                    tone={analysis.failed > 0 ? "bad" : "good"}
                    sub="in one or more subjects"
                  />
                  <Stat
                    label="Class average"
                    value={formatPercent(analysis.classAverageBp, 1)}
                    sub="across all subjects"
                  />
                </div>
                <div className="border-t border-line px-5 py-3.5">
                  <GenerateButtons termId={analysis.term.id} isPublished={analysis.term.isPublished} />
                </div>
              </Card>

              <div className="grid items-start gap-5 lg:grid-cols-2">
                <Card>
                  <CardHead
                    title="Subject-wise"
                    hint="Weakest pass rate first — where teaching needs attention"
                    action={<TrendingDown className="size-4 text-ink-3" />}
                  />
                  {analysis.subjects.length === 0 ? (
                    <Empty title="No marks entered yet" />
                  ) : (
                    <ul className="divide-y divide-line">
                      {analysis.subjects.map((s) => (
                        <li key={s.subject} className="px-5 py-2.5">
                          <div className="flex items-baseline justify-between gap-3">
                            <p className="text-[13.5px] font-medium">{s.subject}</p>
                            <p className="tnum text-[12.5px]">
                              <span
                                className={
                                  s.passRateBp >= 9000
                                    ? "font-semibold text-good"
                                    : s.passRateBp >= 7000
                                      ? "text-marigold-ink"
                                      : "font-semibold text-overdue"
                                }
                              >
                                {formatPercent(s.passRateBp, 0)}
                              </span>
                              <span className="text-ink-3"> pass</span>
                            </p>
                          </div>
                          <Meter
                            valueBp={s.passRateBp}
                            tone={s.passRateBp >= 9000 ? "good" : s.passRateBp >= 7000 ? "warn" : "bad"}
                            className="mt-1.5"
                          />
                          <p className="mt-1 text-[11.5px] text-ink-3">
                            average {formatPercent(s.averageBp, 0)} · highest {s.highest} · {s.appeared}{" "}
                            appeared
                          </p>
                        </li>
                      ))}
                    </ul>
                  )}
                </Card>

                <Card>
                  <CardHead title="Toppers" hint="Ties share a rank, as they should" action={<Award className="size-4 text-ink-3" />} />
                  {analysis.toppers.length === 0 ? (
                    <Empty title="No complete results yet" />
                  ) : (
                    <ul className="divide-y divide-line">
                      {analysis.toppers.map((t) => (
                        <li key={t.studentId} className="flex items-center gap-3 px-5 py-2.5">
                          <span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-brand-light text-[12px] font-bold text-brand-ink tnum">
                            {t.rank}
                          </span>
                          <div className="min-w-0 flex-1">
                            <Link
                              href={`/app/students/${t.studentId}`}
                              className="truncate text-[13.5px] font-medium hover:text-brand hover:underline"
                            >
                              {t.name}
                            </Link>
                            <p className="text-[11.5px] text-ink-3">
                              Roll {t.rollNumber ?? "—"}
                              {t.sectionName ? ` · ${t.sectionName}` : ""}
                            </p>
                          </div>
                          <div className="text-right">
                            <p className="tnum text-[13.5px] font-semibold">
                              {formatPercent(t.totals.percentBp, 1)}
                            </p>
                            <p className="text-[11px] text-ink-3">{t.totals.grade ?? "—"}</p>
                          </div>
                        </li>
                      ))}
                    </ul>
                  )}
                </Card>
              </div>
            </>
          )}
        </div>
      </div>
    </>
  );
}
