/**
 * Putting subjects into periods without asking anybody to be in two rooms at once.
 * Pure.
 *
 * The demo school's timetable was generated by two independent round-robins — one
 * choosing the subject for a period, another choosing the teacher — so 986 of its
 * 1,012 periods were taken by somebody not assigned to that subject at all. Making
 * the teacher follow the subject fixed that and immediately produced the opposite
 * problem: 508 periods where one teacher was wanted in two classrooms at the same
 * time, because each subject has one teacher and the same slot came up in several
 * classes.
 *
 * There is no way around that with arithmetic. It needs scheduling: walk the slots
 * and, for each one, choose a subject whose teacher is actually free. Greedy and
 * deterministic — the same inputs give the same timetable, which matters because a
 * school that regenerates its timetable should not find every room changed.
 *
 * What it will not do is pretend. A slot it cannot fill without a clash comes back
 * as unfilled, and the caller reports the number rather than quietly putting
 * somebody in two places.
 */

export type Slot = { sectionId: string; dayOfWeek: number; period: number };

export type SectionSubjects = {
  sectionId: string;
  /** in the order the school would like them weighted — earlier ones get more periods */
  subjects: { subjectId: string; staffId: string | null }[];
};

export type Placed = Slot & { subjectId: string; staffId: string | null };

export type Timetable = {
  entries: Placed[];
  unfilled: Slot[];
  /** always 0 — kept so a caller can assert on it rather than trusting this comment */
  clashes: number;
  /** the heaviest week any one teacher ended up with */
  busiestTeacherPeriods: number;
};

const MAX_SAME_SUBJECT_PER_DAY = 2;

/**
 * A teacher's week has a ceiling.
 *
 * Without one, greedy filling put a single teacher in all 44 periods of the week —
 * arithmetically valid, humanly absurd, and the sort of thing a principal spots
 * immediately. 30 of 44 is a heavy but real load for a school teacher.
 */
const DEFAULT_MAX_PERIODS_PER_TEACHER = 30;

/**
 * Fill the given slots.
 *
 * `slots` decides the shape of the week — six days, eight periods, four on Saturday,
 * whatever the school does. This only decides what goes in them.
 */
export function buildTimetable(params: {
  slots: Slot[];
  sections: SectionSubjects[];
  maxPeriodsPerTeacher?: number;
}): Timetable {
  const maxLoad = params.maxPeriodsPerTeacher ?? DEFAULT_MAX_PERIODS_PER_TEACHER;
  const bySection = new Map(params.sections.map((s) => [s.sectionId, s.subjects]));
  const sectionOrder = params.sections.map((s) => s.sectionId);

  // A teacher is busy at a (day, period) once. Free periods are the whole game.
  const busy = new Set<string>();
  const perSectionDay = new Map<string, number>(); // sectionId|day|subjectId → count
  const used = new Map<string, number>();          // sectionId|subjectId → count, to spread the week
  const load = new Map<string, number>();          // staffId → periods this week

  const entries: Placed[] = [];
  const unfilled: Slot[] = [];

  // Sorted so the result does not depend on the order the caller happened to build
  // the slots in — the same school gets the same timetable twice.
  const slots = [...params.slots].sort(
    (a, b) =>
      a.dayOfWeek - b.dayOfWeek ||
      a.period - b.period ||
      sectionOrder.indexOf(a.sectionId) - sectionOrder.indexOf(b.sectionId),
  );

  for (const slot of slots) {
    const subjects = bySection.get(slot.sectionId) ?? [];
    if (subjects.length === 0) {
      unfilled.push(slot);
      continue;
    }

    // Least-used subject first, so the week ends up spread rather than front-loaded
    // with whatever was first in the list; then the teacher with the lighter week, so
    // the load spreads across the staff room too.
    const candidates = [...subjects].sort((a, b) => {
      const ua = used.get(`${slot.sectionId}|${a.subjectId}`) ?? 0;
      const ub = used.get(`${slot.sectionId}|${b.subjectId}`) ?? 0;
      if (ua !== ub) return ua - ub;
      const la = a.staffId ? (load.get(a.staffId) ?? 0) : 0;
      const lb = b.staffId ? (load.get(b.staffId) ?? 0) : 0;
      if (la !== lb) return la - lb;
      return subjects.indexOf(a) - subjects.indexOf(b);
    });

    let placed: Placed | null = null;
    for (const relax of [false, true]) {
      for (const candidate of candidates) {
        const dayKey = `${slot.sectionId}|${slot.dayOfWeek}|${candidate.subjectId}`;
        if (!relax && (perSectionDay.get(dayKey) ?? 0) >= MAX_SAME_SUBJECT_PER_DAY) continue;

        const busyKey = candidate.staffId ? `${candidate.staffId}|${slot.dayOfWeek}|${slot.period}` : null;
        if (busyKey && busy.has(busyKey)) continue;
        // The cap is a preference like twice-a-day: it gives way before a period is
        // left empty, but not before a lighter-loaded colleague has been tried.
        if (!relax && candidate.staffId && (load.get(candidate.staffId) ?? 0) >= maxLoad) continue;

        if (busyKey) busy.add(busyKey);
        if (candidate.staffId) load.set(candidate.staffId, (load.get(candidate.staffId) ?? 0) + 1);
        perSectionDay.set(dayKey, (perSectionDay.get(dayKey) ?? 0) + 1);
        used.set(`${slot.sectionId}|${candidate.subjectId}`, (used.get(`${slot.sectionId}|${candidate.subjectId}`) ?? 0) + 1);
        placed = { ...slot, subjectId: candidate.subjectId, staffId: candidate.staffId };
        break;
      }
      if (placed) break;
      // Nothing fitted with the same-subject-twice-a-day rule. That rule is a
      // preference; a free period is not. Try again without it before giving up.
    }

    if (placed) entries.push(placed);
    else unfilled.push(slot);
  }

  return {
    entries,
    unfilled,
    clashes: countClashes(entries),
    busiestTeacherPeriods: load.size === 0 ? 0 : Math.max(...load.values()),
  };
}

/** How many entries put a teacher somewhere they already are. Should always be 0. */
export function countClashes(entries: Placed[]): number {
  const seen = new Set<string>();
  let clashes = 0;
  for (const e of entries) {
    if (!e.staffId) continue;
    const key = `${e.staffId}|${e.dayOfWeek}|${e.period}`;
    if (seen.has(key)) clashes += 1;
    else seen.add(key);
  }
  return clashes;
}

/** The ordinary Indian school week: six days, eight periods, four on Saturday. */
export function weekOfSlots(
  sectionIds: string[],
  periodsPerDay: (dayOfWeek: number) => number = (d) => (d === 6 ? 4 : 8),
  days: number[] = [1, 2, 3, 4, 5, 6],
): Slot[] {
  const slots: Slot[] = [];
  for (const dayOfWeek of days) {
    for (let period = 1; period <= periodsPerDay(dayOfWeek); period++) {
      for (const sectionId of sectionIds) slots.push({ sectionId, dayOfWeek, period });
    }
  }
  return slots;
}

/**
 * Whether one period can be put where somebody is asking to put it.
 *
 * The whole-week scheduler guarantees no clashes by construction, but a school
 * editing a single cell needs the same guarantee one period at a time — and the
 * useful answer is not "no", it is "no, because she is with 7B then".
 */
export function canPlacePeriod(params: {
  staffId: string | null;
  dayOfWeek: number;
  period: number;
  /** every other period in the school at that time, excluding the one being edited */
  elsewhere: { staffId: string | null; sectionName: string }[];
}): { allowed: boolean; reason: string | null } {
  if (!params.staffId) return { allowed: true, reason: null };
  const clash = params.elsewhere.find((e) => e.staffId === params.staffId);
  if (clash) {
    return {
      allowed: false,
      reason: `They are already taking ${clash.sectionName} in period ${params.period} that day.`,
    };
  }
  return { allowed: true, reason: null };
}

/** A teacher's week, for showing a load before it is committed. */
export function teacherLoad(entries: { staffId: string | null }[]): Map<string, number> {
  const load = new Map<string, number>();
  for (const e of entries) {
    if (!e.staffId) continue;
    load.set(e.staffId, (load.get(e.staffId) ?? 0) + 1);
  }
  return load;
}
